[package]
name = "rust_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28.2", features = ["full"] }
tokio-tungstenite = "0.19.0"
futures-channel = "0.3.28"
futures-util = "0.3.28"
